version: '2'

services:

#-------------------------------------------------------------------
# ALL FEATURES
#-------------------------------------------------------------------
  consul:
    build:
      context: ./centos-consul
    ports:
      - "8500:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_OPTIONS=${CONSUL_OPTIONS}               # minimal server options

  application:
    depends_on:
      - consul
    build:
      context: ./centos-application
    ports:
      - "${APPLICATION_PORT}:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_APPLICATION}:/home/docker/workspace
    environment:
      - SSH_AUTHORIZED_KEYS=${SSH_AUTHORIZED_KEYS}
      - SSH_USER=${SSH_USER}
      - SSH_USER_PASSWORD=${SSH_USER_PASSWORD}
      - SSH_USER_PASSWORD_HASHED=${SSH_USER_PASSWORD_HASHED}
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
      - CONSUL_APPLICATION_SERVICENAME=${CONSUL_APPLICATION_SERVICENAME}       # consul service name
      - CONSUL_APPLICATION_SERVICETAGS=${CONSUL_APPLICATION_SERVICETAGS}       # consul service tag
      - CONSUL_APPLICATION_SERVICEPORT=${CONSUL_APPLICATION_SERVICEPORT}       # consul service port
      - CONSUL_APPLICATION_CHECKTYPE=${CONSUL_APPLICATION_CHECKTYPE}           # consul health check type
    tty: true
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# LITE EDITION
#-------------------------------------------------------------------
  application-lite:
    depends_on:
      - consul
    build:
      context: ./centos-application-lite
    ports:
      - "${APPLICATION_PORT}:22"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_APPLICATION}:/home/docker/workspace
    environment:
      - SSH_AUTHORIZED_KEYS=${SSH_AUTHORIZED_KEYS}
      - SSH_USER=${SSH_USER}
      - SSH_USER_PASSWORD=${SSH_USER_PASSWORD}
      - SSH_USER_PASSWORD_HASHED=${SSH_USER_PASSWORD_HASHED}
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
      - CONSUL_APPLICATION_SERVICENAME=${CONSUL_APPLICATION_SERVICENAME}                             # consul service name
      - CONSUL_APPLICATION_SERVICETAGS=${CONSUL_APPLICATION_SERVICETAGS}                             # consul service tag
      - CONSUL_APPLICATION_SERVICEPORT=${CONSUL_APPLICATION_SERVICEPORT}                             # consul service port
      - CONSUL_APPLICATION_CHECKTYPE=${CONSUL_APPLICATION_CHECKTYPE}                                 # consul health check type
    tty: true
    networks:
      - frontend
      - backend

#-------------------------------------------------------------------
# DATABASE
#-------------------------------------------------------------------
  postgres:
    build: ./postgres
    links:
      - application
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_SAVE}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  application:
    driver: "local"
  application-lite:
    driver: "local"
  postgres:
    driver: "local"
