version: '3'

services:
  consul:
    image: zeroc0d3lab/centos-consul
    ports:
      - "8500:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

  mongodb:
    depends_on:
      - consul
    build:
      context: .
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /host/data:/data/db                               # volume for data
    environment:
      - CONSUL_AGENT=${CONSUL_MONGODB_AGENT}               # consul agent hostname/IP
      #- CONSUL_PORT=8500                                  # consul agent port
      #- CONSUL_KEYPREFIX=path/prefix/                     # consul key prefix path
      - CONSUL_SERVICENAME=mongodb                         # consul service name
      - CONSUL_SERVICETAGS=dev                             # consul service tag
      - CONSUL_SERVICEPORT=27017                           # consul service port
      - CONSUL_CHECKTYPE=tcp                               # consul health check type
      #- MONGODB_PROFILE=my-small                          # default configuration profile to use (my-small, my-medium ...)
      #- MONGODB_CONFIGSCRIPT=${MONGODB_CONFIGSCRIPT}      # custom configuration script
