version: '3.2'

services:
  base:
    build:
      context: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - S6OVERLAY_VERSION=${S6OVERLAY_VERSION}
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=${S6_BEHAVIOUR_IF_STAGE2_FAILS}
      - LANG=${LANG}
      - LC_ALL=${LC_ALL}
      - LANGUAGE=${LANGUAGE}
      - TERM=${TERM}